name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Building..."
      
      - name: Save build status
        if: always()
        run: echo "build_status=${{ job.status }}" >> $GITHUB_STATE

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test
        run: echo "Testing..."
      
      - name: Save test status
        if: always()
        run: echo "test_status=${{ job.status }}" >> $GITHUB_STATE

  overall_status:
    name: Determine Overall Status
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Check Status
        id: check_status
        run: |
          if grep -q "build_status=failure" $GITHUB_STATE || grep -q "test_status=failure" $GITHUB_STATE; then
            echo "Overall Status: fail"
          else
            echo "Overall Status: pass"
          fi

  notify:
    name: Notify Overall Status
    runs-on: ubuntu-latest
    needs: overall_status

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call Composite Action
        if: always()
        uses: ./.github/actions/build_and_notify
        with:
          action-name: ${{ github.workflow }}
          overall-status: '${{ needs.overall_status.outputs.check_status }}'
