name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build
        run: echo "Building..."
      
      - name: Save build status
        id: save_build_status
        if: always()
        run: echo "var2=${{ job.status }}" >> status.txt

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Test
        run: |
          echo "Testing..."
          exit 1
      
      - name: Save test status
        id: save_test_status
        if: always()
        run: echo "var1=${{ job.status }}" >> status.txt

  overall_status:
    name: Determine Overall Status
    runs-on: ubuntu-latest
    needs: [build, test]
    if: always()
    outputs:
      overall-status: ${{ needs.overall_status.outputs.overall-status }}

    steps:
      - name: Set Overall Status
        id: set_overall_status
        run: |
          build_status="${{ needs.build.outputs.var2 }}"
          test_status="${{ needs.test.outputs.var1 }}"
          # Check if both build and test were successful
          if [ "$build_status" == "success" ] && [ "$test_status" == "success" ]; then
            echo "Overall Status: pass"
            echo "::set-output name=overall-status::pass"
          else
            echo "Overall Status: fail"
            echo "::set-output name=overall-status::fail"
          fi

  run_composite_action:
    name: Run the Composite Action
    if: always()
    needs: [overall_status]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run the Composite Action
        uses: ./.github/actions/build_and_notify
        with:
          action-name: ${{ github.workflow }}
          overall-status: ${{ needs.overall_status.outputs.overall-status }}
