name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build
        run: echo "Building..."
      
      - name: Save build status
        id: save_build_status
        if: always()
        run: echo "var2=${{ job.status }}" >> $GITHUB_STATE

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Test
        run: |
          echo "Testing..."
          exit 1
      
      - name: Save test status
        id: save_test_status
        if: always()
        run: echo "var1=${{ job.status }}" >> $GITHUB_STATE

  overall_status:
    name: Determine Overall Status
    runs-on: ubuntu-latest
    needs: [build, test]
    if: always()
    outputs:
      overall-status: ${{ needs.overall_status.outputs.overall-status }} # Pass overall status as an output

    steps:
      - name: Set Overall Status
        id: set_overall_status
        run: |
          build_status=$(echo "${{ needs.build.outputs.var2 }}")
          test_status=$(echo "${{ needs.test.outputs.var1 }}")
          # Check if both build and test were successful
          if [ "$build_status" == "success" ] && [ "$test_status" == "success" ]; then
            echo "Overall Status: pass"
            echo "::set-output name=overall-status::pass" # Set overall status as an output
          else
            echo "Overall Status: fail"
            echo "::set-output name=overall-status::fail" # Set overall status as an output
          fi
