name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build
        run: echo "Building..."
      
      - name: Save build status
        id: save_build_status
        if: always()
        run: echo "var2=${{ job.status }}" >> $GITHUB_STATE

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Test
        run: |
          echo "Testing..."
          exit 1
      
      - name: Save test status
        id: save_test_status
        if: always()
        run: echo "var1=${{ job.status }}" >> $GITHUB_STATE

  overall_status:
    name: Determine Overall Status
    runs-on: ubuntu-latest
    needs: [build, test]
    if: always()

    steps:
      - name: Set Overall Status
        id: set_overall_status
        run: |
          build_status=$(echo "${{ needs.build.outputs.var2 }}")
          test_status=$(echo "${{ needs.test.outputs.var1 }}")
          # Check if both build and test were successful
          if [ "$build_status" == "success" ] && [ "$test_status" == "success" ]; then
            echo "Overall Status: pass"
            echo "status=pass" >> $GITHUB_ENV
          else
            echo "Overall Status: fail"
            echo "status=fail" >> $GITHUB_ENV
          fi
  run_composite_action:
    name: Run the Composite Action
    if: always()
    needs: [overall_status]
    runs-on: ubuntu-latest
    env:
      OVERALL_STATUS: '' # Initialize the environment variable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Overall Status as Environment Variable
        run: echo "OVERALL_STATUS=${{ env.status }}" >> $GITHUB_ENV

      - name: Run the Composite Action
        uses: ./.github/actions/build_and_notify
        with:
          action-name: ${{ github.workflow }}
