name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.save_build_status.outputs.build_status }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building..."

      - name: Save build status
        id: save_build_status
        if: always()
        run: echo "build_status=${{ job.status }}" >> $GITHUB_OUTPUT

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    outputs:
      test_status: ${{ steps.save_test_status.outputs.test_status }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          echo "Testing..."
          exit 1  # Simulating a failure for demonstration

      - name: Save test status
        id: save_test_status
        if: always()
        run: echo "test_status=${{ job.status }}" >> $GITHUB_OUTPUT

  overall_status:
    name: Determine Overall Status
    runs-on: ubuntu-latest
    needs: [build, test]
    if: always()
    outputs:
      overall_status: ${{ steps.set_overall_status.outputs.overall_status }}

    steps:
      - name: Set Overall Status
        id: set_overall_status
        run: |
          build_status="${{ needs.build.outputs.build_status }}"
          test_status="${{ needs.test.outputs.test_status }}"
          echo "Build Status: $build_status"
          echo "Test Status: $test_status"
          
          if [ "$build_status" == "success" ] && [ "$test_status" == "success" ]; then
            overall_status="pass"
          else
            overall_status="fail"
          fi

          echo "Overall Status: $overall_status"
          echo "overall_status=$overall_status" >> $GITHUB_OUTPUT

  notify:
    name: Notify
    if: always()
    runs-on: ubuntu-latest
    needs: overall_status

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Notifications
        uses: ./.github/actions/build_and_notify
        with:
          action-name: Build and Test Notification
          overall-status: ${{ needs.overall_status.outputs.overall_status }}
