name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building..."

      - name: Save build status
        id: save_build_status
        if: always()
        run: echo "var2=${{ job.status }}" >> ${{ github.workspace }}/build_status.txt


  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          echo "Testing..."
          exit 1
      
      - name: Save test status
        id: save_test_status
        if: always()
        run: echo "var1=${{ job.status }}" >> ${{ github.workspace }}/test_status.txt

  overall_status:
    name: Determine Overall Status
    runs-on: ubuntu-latest
    needs: [build, test]
    if: always()

    steps:
      - name: Set Overall Status
        id: set_overall_status
        run: |
          build_status=$(echo "${{ needs.build.outputs.var2 }}")
          test_status=$(echo "${{ needs.test.outputs.var1 }}")
          echo "Build Status: $build_status"
          echo "Test Status: $test_status"
          if [ "$build_status" == "success" ] && [ "$test_status" == "success" ]; then
            echo "Overall Status: pass"
            echo "status=pass" >> $GITHUB_ENV
            echo "Overall Status: pass" >> ${{ github.workspace }}/overall_status.txt
            echo "::set-output name=status_file_path::${{ github.workspace }}/overall_status.txt"  # Pass the path as output
            echo "pass" > ${{ github.workspace }}/overall_status.txt  # Save overall status directly
          else
            echo "Overall Status: fail"
            echo "status=fail" >> $GITHUB_ENV
            echo "Overall Status: fail" >> ${{ github.workspace }}/overall_status.txt
            echo "::set-output name=status_file_path::${{ github.workspace }}/overall_status.txt"  # Pass the path as output
            echo "fail" > ${{ github.workspace }}/overall_status.txt  # Save overall status directly
          fi

  run_composite_action:
    name: Run the Composite Action
    if: always()
    needs: [overall_status]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read overall status
        id: read_overall_status
        run: |
          overall_status=$(cat ${{ github.workspace }}/overall_status.txt)
          echo "::set-output name=overall_status::$overall_status"  # Pass the overall status as output

      - name: Run the Composite Action
        uses: ./.github/actions/build_and_notify
        with:
          action-name: ${{ github.workflow }}
          overall-status: ${{ steps.read_overall_status.outputs.overall_status }}
