name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Building..."
      
      - name: Save build status
        id: save_build_status
        if: always()
        run: echo "var2=${{ job.status }}" >> $GITHUB_STATE

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test
        run: |
          echo "Testing..."
          exit 1
      
      - name: Save test status
        id: save_test_status
        if: always()
        run: echo "var1=${{ job.status }}" >> $GITHUB_STATE

  overall_status:
    name: Determine Overall Status
    runs-on: ubuntu-latest
    needs: [build, test]
    if: always()

    steps:
      - name: Set Overall Status
        id: set_overall_status
        run: |
          build_status=$(grep -oP '^var2=\K\w+' $GITHUB_STATE)
          test_status=$(grep -oP '^var1=\K\w+' $GITHUB_STATE)
          if [ "$build_status" == "success" ] && [ "$test_status" == "success" ]; then
            echo "Overall Status: pass"
          else
            echo "Overall Status: fail"
          fi
