name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_STATUS_FILE: ${{ github.workspace }}/build_status.txt
  TEST_STATUS_FILE: ${{ github.workspace }}/test_status.txt
  OVERALL_STATUS_FILE: ${{ github.workspace }}/overall_status.txt

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: echo "Building..."

      - name: Save build status
        id: save_build_status
        if: always()
        run: echo "var2=${{ job.status }}" >> $BUILD_STATUS_FILE


  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          echo "Testing..."
          exit 1
      
      - name: Save test status
        id: save_test_status
        if: always()
        run: echo "var1=${{ job.status }}" >> $TEST_STATUS_FILE

  overall_status:
    name: Determine Overall Status
    runs-on: ubuntu-latest
    needs: [build, test]
    if: always()

    steps:
      - name: Set Overall Status
        id: set_overall_status
        run: |
          build_status=$(echo "${{ needs.build.outputs.var2 }}")
          test_status=$(echo "${{ needs.test.outputs.var1 }}")
          echo "Build Status: $build_status"
          echo "Test Status: $test_status"
          if [ "$build_status" == "success" ] && [ "$test_status" == "success" ]; then
            echo "Overall Status: pass"
            echo "status=pass" >> $GITHUB_ENV
            echo "Overall Status: pass" >> $OVERALL_STATUS_FILE
            echo "::set-output name=status_file_path::$OVERALL_STATUS_FILE"  # Pass the path as output
            echo "pass" > $OVERALL_STATUS_FILE  # Save overall status directly
          else
            echo "Overall Status: fail"
            echo "status=fail" >> $GITHUB_ENV
            echo "Overall Status: fail" >> $OVERALL_STATUS_FILE
            echo "::set-output name=status_file_path::$OVERALL_STATUS_FILE"  # Pass the path as output
            echo "fail" > $OVERALL_STATUS_FILE  # Save overall status directly
          fi
